// Code generated by MockGen. DO NOT EDIT.
// Source: oxide_client.go
//
// Generated by this command:
//
//	mockgen -source=oxide_client.go -destination=oxide_client_mock_test.go -package=oxidesecrets -mock_names=oxideClient=MockOxideClient
//

// Package oxidesecrets is a generated GoMock package.
package oxidesecrets

import (
	context "context"
	http "net/http"
	reflect "reflect"

	oxide "github.com/oxidecomputer/oxide.go/oxide"
	gomock "go.uber.org/mock/gomock"
)

// MockOxideClient is a mock of oxideClient interface.
type MockOxideClient struct {
	ctrl     *gomock.Controller
	recorder *MockOxideClientMockRecorder
	isgomock struct{}
}

// MockOxideClientMockRecorder is the mock recorder for MockOxideClient.
type MockOxideClientMockRecorder struct {
	mock *MockOxideClient
}

// NewMockOxideClient creates a new mock instance.
func NewMockOxideClient(ctrl *gomock.Controller) *MockOxideClient {
	mock := &MockOxideClient{ctrl: ctrl}
	mock.recorder = &MockOxideClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOxideClient) EXPECT() *MockOxideClientMockRecorder {
	return m.recorder
}

// CurrentUserAccessTokenDelete mocks base method.
func (m *MockOxideClient) CurrentUserAccessTokenDelete(arg0 context.Context, arg1 oxide.CurrentUserAccessTokenDeleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUserAccessTokenDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CurrentUserAccessTokenDelete indicates an expected call of CurrentUserAccessTokenDelete.
func (mr *MockOxideClientMockRecorder) CurrentUserAccessTokenDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserAccessTokenDelete", reflect.TypeOf((*MockOxideClient)(nil).CurrentUserAccessTokenDelete), arg0, arg1)
}

// CurrentUserView mocks base method.
func (m *MockOxideClient) CurrentUserView(arg0 context.Context) (*oxide.CurrentUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUserView", arg0)
	ret0, _ := ret[0].(*oxide.CurrentUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUserView indicates an expected call of CurrentUserView.
func (mr *MockOxideClientMockRecorder) CurrentUserView(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserView", reflect.TypeOf((*MockOxideClient)(nil).CurrentUserView), arg0)
}

// MakeRequest mocks base method.
func (m *MockOxideClient) MakeRequest(arg0 context.Context, arg1 oxide.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequest", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequest indicates an expected call of MakeRequest.
func (mr *MockOxideClientMockRecorder) MakeRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequest", reflect.TypeOf((*MockOxideClient)(nil).MakeRequest), arg0, arg1)
}
