= vault-plugin-secrets-oxide

A Vault/OpenBao secrets engine that provides ephemeral Oxide access credentials.

[source,mermaid]
----
sequenceDiagram
	participant vault-user
	participant vault-core
	participant vault-plugin
	participant nexus

	vault-user ->> vault-core: Request Oxide token
	vault-core ->> vault-plugin: Request Oxide token
	vault-plugin ->> nexus: Request device token
	nexus ->> vault-plugin: Return Oxide token
	vault-plugin ->> vault-core: Return Oxide token
	vault-core ->> vault-user: Return Oxide token
----

== Usage

=== Administrator

To configure the plugin, create at least one `principal`. A `principal` represents a single Oxide user for a single silo, and is used by the plugin to generate short-lived access tokens representing the same user as the `principal`.

[source,shell]
----
$ vault write oxide/principal/my-principal \
    host=https://oxide.sys.r3.oxide-preview.com \
    token="$OXIDE_PRINCIPAL_TOKEN" \
    default_ttl=15m \
    max_ttl=1h
----

=== End user

Once the plugin is configured, Vault users with read access to the `principal` can request a short-lived Oxide access token:

[source,shell]
----
$ vault read oxide/creds/my-principal

Key                Value
---                -----
lease_id           oxide/creds/my-principal/vIdIEn04G2jVapFC2PB1uXSg
lease_duration     15m
lease_renewable    false
access_token       oxide-token-...
time_expires       2026-09-08T22:18:09.793941Z
token_id           05091d43-6824-4adc-8eb6-38068c910500
token_type         bearer
----

== Caveats

* Identity. Each `principal` is configured with a long-lived Oxide token by the Vault administrator, and is used to provision ephemeral Oxide tokens for Vault users. The short-lived tokens represent the same Oxide user that generated the long-lived token, and inherit the same permissions as that user.

* Revocation. The ephemeral Oxide tokens provided by the plugin can be used to generate more ephemeral Oxide tokens outside the plugin. If the original ephemeral token generated by the plugin is revoked, these derived tokens won't be automatically revoked. Note that the expiration time of these derived tokens can't be set to a time later than the expiration of the original ephemeral token generated by the plugin.
